# Site settings
title: "相飞简历"
description: "参考 Jekyll Resume Template"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
# Resume settings
resume_avatar:                  "true"
resume_name:                    "相飞"
resume_title:                   "运维开发"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "1320959247@qq.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "13388420160"
resume_contact_address:         "杭州"

resume_header_contact_info:     '<h4><div style="float:right">address: 杭州 </div><br/><div style="float:right"> tel: 13388420160 </div> <br/> <div style="float:right"> mail: 1320959247@qq.com</div></h4>'

display_header_contact_info:    "true"

resume_header_intro: "<p>4年运维经验,熟悉tomcat, jboss, nginx ,kafka, mysql , zookeeper, redis ,lvs , openstack , opennebula ,ceph , kvm , k8s 。5年开发经验擅长ruby ,python  ,jquery , vue.js ,java(开始工作3年用过,其他时间都是python和ruby)</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://xiangfei.github.io/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
